export const actionTypes = {
    TOGGLE_MODE : 'TOGGLE_MODE',
    // LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL'
    USER_INPUT: 'USER_INPUT',

    FETCH_DATA_START: 'FETCH_DATA_START',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILED : 'FETCH_DATA_FAILED',

    ADD_TO_FAVOURITE: 'ADD_TO_FAVOURITE'

}